// Curated UN/LOCODE list for the Origin / Destination pickers on the quote
// builder. This is NOT the full ~120k UNECE set — it's a hand-picked list of
// the major sea ports and international airports that ExPac actually quotes,
// weighted to the South Africa <-> China lanes and the main global hubs.
//
// The builder fields still accept free text, so anything missing here can be
// typed in directly (start with the 5-character code). Add rows below as new
// lanes come up. Airport codes are ISO-2 country + 3-letter IATA.

export interface Locode {
  /** 5-char UN/LOCODE, e.g. "ZAJNB". */
  code: string;
  city: string;
  country: string;
}

export const LOCODES: Locode[] = [
  // ---- South Africa ----
  { code: "ZADUR", city: "Durban", country: "South Africa" },
  { code: "ZACPT", city: "Cape Town", country: "South Africa" },
  { code: "ZAJNB", city: "Johannesburg (OR Tambo)", country: "South Africa" },
  { code: "ZAPLZ", city: "Gqeberha (Port Elizabeth)", country: "South Africa" },
  { code: "ZAZBA", city: "Coega / Ngqura", country: "South Africa" },
  { code: "ZAELS", city: "East London", country: "South Africa" },
  { code: "ZARCB", city: "Richards Bay", country: "South Africa" },
  { code: "ZASDB", city: "Saldanha Bay", country: "South Africa" },
  { code: "ZAMSU", city: "Mossel Bay", country: "South Africa" },
  { code: "ZAGRJ", city: "George", country: "South Africa" },
  { code: "ZABFN", city: "Bloemfontein", country: "South Africa" },
  { code: "ZAKIM", city: "Kimberley", country: "South Africa" },
  { code: "ZAPTG", city: "Polokwane", country: "South Africa" },
  { code: "ZAMQP", city: "Mbombela (Kruger Mpumalanga)", country: "South Africa" },
  { code: "ZAUTN", city: "Upington", country: "South Africa" },
  { code: "ZAHDS", city: "Hoedspruit", country: "South Africa" },

  // ---- Southern & East Africa ----
  { code: "NAWVB", city: "Walvis Bay", country: "Namibia" },
  { code: "NAWDH", city: "Windhoek", country: "Namibia" },
  { code: "MZMPM", city: "Maputo", country: "Mozambique" },
  { code: "MZBEW", city: "Beira", country: "Mozambique" },
  { code: "MZMNC", city: "Nacala", country: "Mozambique" },
  { code: "ZWHRE", city: "Harare", country: "Zimbabwe" },
  { code: "ZWBUQ", city: "Bulawayo", country: "Zimbabwe" },
  { code: "ZMLUN", city: "Lusaka", country: "Zambia" },
  { code: "ZMNLA", city: "Ndola", country: "Zambia" },
  { code: "BWGBE", city: "Gaborone", country: "Botswana" },
  { code: "MWLLW", city: "Lilongwe", country: "Malawi" },
  { code: "MWBLZ", city: "Blantyre", country: "Malawi" },
  { code: "LSMSU", city: "Maseru", country: "Lesotho" },
  { code: "SZMTS", city: "Manzini", country: "Eswatini" },
  { code: "KEMBA", city: "Mombasa", country: "Kenya" },
  { code: "KENBO", city: "Nairobi", country: "Kenya" },
  { code: "TZDAR", city: "Dar es Salaam", country: "Tanzania" },
  { code: "MGTMM", city: "Toamasina", country: "Madagascar" },
  { code: "MGTNR", city: "Antananarivo", country: "Madagascar" },
  { code: "MUPLU", city: "Port Louis", country: "Mauritius" },
  { code: "RERUN", city: "Le Port (Reunion)", country: "France" },
  { code: "DJJIB", city: "Djibouti", country: "Djibouti" },
  { code: "ETADD", city: "Addis Ababa", country: "Ethiopia" },
  { code: "SDPZU", city: "Port Sudan", country: "Sudan" },
  { code: "AOLAD", city: "Luanda", country: "Angola" },
  { code: "CGPNR", city: "Pointe-Noire", country: "Congo" },
  { code: "CDMAT", city: "Matadi", country: "DR Congo" },
  { code: "CMDLA", city: "Douala", country: "Cameroon" },
  { code: "GALBV", city: "Libreville", country: "Gabon" },
  { code: "NGLOS", city: "Lagos (Apapa)", country: "Nigeria" },
  { code: "NGONN", city: "Onne", country: "Nigeria" },
  { code: "GHTEM", city: "Tema", country: "Ghana" },
  { code: "GHACC", city: "Accra", country: "Ghana" },
  { code: "CIABJ", city: "Abidjan", country: "Cote d'Ivoire" },
  { code: "TGLFW", city: "Lome", country: "Togo" },
  { code: "BJCOO", city: "Cotonou", country: "Benin" },
  { code: "SNDKR", city: "Dakar", country: "Senegal" },

  // ---- North Africa ----
  { code: "EGALY", city: "Alexandria", country: "Egypt" },
  { code: "EGPSD", city: "Port Said", country: "Egypt" },
  { code: "EGSOK", city: "Ain Sokhna", country: "Egypt" },
  { code: "EGDAM", city: "Damietta", country: "Egypt" },
  { code: "EGCAI", city: "Cairo", country: "Egypt" },
  { code: "MACAS", city: "Casablanca", country: "Morocco" },
  { code: "MAPTM", city: "Tanger Med", country: "Morocco" },
  { code: "DZALG", city: "Algiers", country: "Algeria" },
  { code: "TNRDS", city: "Rades (Tunis)", country: "Tunisia" },
  { code: "LYTIP", city: "Tripoli", country: "Libya" },

  // ---- China ----
  { code: "CNSHA", city: "Shanghai", country: "China" },
  { code: "CNNGB", city: "Ningbo-Zhoushan", country: "China" },
  { code: "CNYTN", city: "Yantian (Shenzhen)", country: "China" },
  { code: "CNSHK", city: "Shekou (Shenzhen)", country: "China" },
  { code: "CNCWN", city: "Chiwan (Shenzhen)", country: "China" },
  { code: "CNSZX", city: "Shenzhen", country: "China" },
  { code: "CNCAN", city: "Guangzhou", country: "China" },
  { code: "CNNSA", city: "Nansha (Guangzhou)", country: "China" },
  { code: "CNTAO", city: "Qingdao", country: "China" },
  { code: "CNXMN", city: "Xiamen", country: "China" },
  { code: "CNDLC", city: "Dalian", country: "China" },
  { code: "CNTSN", city: "Tianjin (Xingang)", country: "China" },
  { code: "CNLYG", city: "Lianyungang", country: "China" },
  { code: "CNFOC", city: "Fuzhou", country: "China" },
  { code: "CNZUH", city: "Zhuhai", country: "China" },
  { code: "CNZJG", city: "Zhangjiagang", country: "China" },
  { code: "CNSWA", city: "Shantou", country: "China" },
  { code: "CNHAK", city: "Haikou", country: "China" },
  { code: "CNNKG", city: "Nanjing", country: "China" },
  { code: "CNWUH", city: "Wuhan", country: "China" },
  { code: "CNCKG", city: "Chongqing", country: "China" },
  { code: "CNCTU", city: "Chengdu", country: "China" },
  { code: "CNHGH", city: "Hangzhou", country: "China" },
  { code: "CNCGO", city: "Zhengzhou", country: "China" },
  { code: "CNKMG", city: "Kunming", country: "China" },
  { code: "CNXIY", city: "Xi'an", country: "China" },
  { code: "CNPEK", city: "Beijing (Capital)", country: "China" },
  { code: "CNPKX", city: "Beijing (Daxing)", country: "China" },
  { code: "HKHKG", city: "Hong Kong", country: "Hong Kong" },
  { code: "MOMFM", city: "Macau", country: "Macau" },
  { code: "TWKHH", city: "Kaohsiung", country: "Taiwan" },
  { code: "TWTPE", city: "Taipei", country: "Taiwan" },
  { code: "TWKEL", city: "Keelung", country: "Taiwan" },
  { code: "TWTXG", city: "Taichung", country: "Taiwan" },

  // ---- South & South-East Asia ----
  { code: "SGSIN", city: "Singapore", country: "Singapore" },
  { code: "MYPKG", city: "Port Klang", country: "Malaysia" },
  { code: "MYTPP", city: "Tanjung Pelepas", country: "Malaysia" },
  { code: "MYPEN", city: "Penang", country: "Malaysia" },
  { code: "MYKUL", city: "Kuala Lumpur", country: "Malaysia" },
  { code: "IDJKT", city: "Jakarta (Tanjung Priok)", country: "Indonesia" },
  { code: "IDCGK", city: "Jakarta (Soekarno-Hatta)", country: "Indonesia" },
  { code: "IDSUB", city: "Surabaya", country: "Indonesia" },
  { code: "THLCH", city: "Laem Chabang", country: "Thailand" },
  { code: "THBKK", city: "Bangkok", country: "Thailand" },
  { code: "VNSGN", city: "Ho Chi Minh City", country: "Vietnam" },
  { code: "VNHPH", city: "Haiphong", country: "Vietnam" },
  { code: "VNHAN", city: "Hanoi", country: "Vietnam" },
  { code: "VNDAD", city: "Da Nang", country: "Vietnam" },
  { code: "PHMNL", city: "Manila", country: "Philippines" },
  { code: "PHCEB", city: "Cebu", country: "Philippines" },
  { code: "KHPNH", city: "Phnom Penh", country: "Cambodia" },
  { code: "KHKOS", city: "Sihanoukville", country: "Cambodia" },
  { code: "MMRGN", city: "Yangon", country: "Myanmar" },
  { code: "KRPUS", city: "Busan", country: "South Korea" },
  { code: "KRINC", city: "Incheon", country: "South Korea" },
  { code: "KRICN", city: "Seoul (Incheon Airport)", country: "South Korea" },
  { code: "JPYOK", city: "Yokohama", country: "Japan" },
  { code: "JPTYO", city: "Tokyo", country: "Japan" },
  { code: "JPNRT", city: "Tokyo (Narita)", country: "Japan" },
  { code: "JPHND", city: "Tokyo (Haneda)", country: "Japan" },
  { code: "JPUKB", city: "Kobe", country: "Japan" },
  { code: "JPNGO", city: "Nagoya", country: "Japan" },
  { code: "JPOSA", city: "Osaka", country: "Japan" },
  { code: "JPKIX", city: "Osaka (Kansai)", country: "Japan" },
  { code: "INBOM", city: "Mumbai", country: "India" },
  { code: "INNSA", city: "Nhava Sheva (JNPT)", country: "India" },
  { code: "INMUN", city: "Mundra", country: "India" },
  { code: "INPAV", city: "Pipavav", country: "India" },
  { code: "INMAA", city: "Chennai", country: "India" },
  { code: "INCCU", city: "Kolkata", country: "India" },
  { code: "INCOK", city: "Cochin", country: "India" },
  { code: "INDEL", city: "New Delhi", country: "India" },
  { code: "INBLR", city: "Bengaluru", country: "India" },
  { code: "INHYD", city: "Hyderabad", country: "India" },
  { code: "LKCMB", city: "Colombo", country: "Sri Lanka" },
  { code: "BDCGP", city: "Chattogram (Chittagong)", country: "Bangladesh" },
  { code: "BDDAC", city: "Dhaka", country: "Bangladesh" },
  { code: "PKKHI", city: "Karachi", country: "Pakistan" },
  { code: "PKBQM", city: "Port Qasim", country: "Pakistan" },

  // ---- Middle East ----
  { code: "AEJEA", city: "Jebel Ali (Dubai)", country: "United Arab Emirates" },
  { code: "AEDXB", city: "Dubai", country: "United Arab Emirates" },
  { code: "AEAUH", city: "Abu Dhabi", country: "United Arab Emirates" },
  { code: "AESHJ", city: "Sharjah", country: "United Arab Emirates" },
  { code: "SAJED", city: "Jeddah", country: "Saudi Arabia" },
  { code: "SADMM", city: "Dammam", country: "Saudi Arabia" },
  { code: "SARUH", city: "Riyadh", country: "Saudi Arabia" },
  { code: "QADOH", city: "Doha", country: "Qatar" },
  { code: "OMSLL", city: "Salalah", country: "Oman" },
  { code: "OMMCT", city: "Muscat", country: "Oman" },
  { code: "KWKWI", city: "Kuwait", country: "Kuwait" },
  { code: "BHBAH", city: "Bahrain", country: "Bahrain" },
  { code: "IRBND", city: "Bandar Abbas", country: "Iran" },
  { code: "JOAQJ", city: "Aqaba", country: "Jordan" },
  { code: "ILHFA", city: "Haifa", country: "Israel" },
  { code: "ILASH", city: "Ashdod", country: "Israel" },
  { code: "TRIST", city: "Istanbul", country: "Turkey" },
  { code: "TRMER", city: "Mersin", country: "Turkey" },
  { code: "TRIZM", city: "Izmir", country: "Turkey" },

  // ---- Europe ----
  { code: "NLRTM", city: "Rotterdam", country: "Netherlands" },
  { code: "NLAMS", city: "Amsterdam (Schiphol)", country: "Netherlands" },
  { code: "BEANR", city: "Antwerp", country: "Belgium" },
  { code: "BEZEE", city: "Zeebrugge", country: "Belgium" },
  { code: "BEBRU", city: "Brussels", country: "Belgium" },
  { code: "DEHAM", city: "Hamburg", country: "Germany" },
  { code: "DEBRV", city: "Bremerhaven", country: "Germany" },
  { code: "DEWVN", city: "Wilhelmshaven", country: "Germany" },
  { code: "DEFRA", city: "Frankfurt", country: "Germany" },
  { code: "DEMUC", city: "Munich", country: "Germany" },
  { code: "GBFXT", city: "Felixstowe", country: "United Kingdom" },
  { code: "GBSOU", city: "Southampton", country: "United Kingdom" },
  { code: "GBLGP", city: "London Gateway", country: "United Kingdom" },
  { code: "GBLIV", city: "Liverpool", country: "United Kingdom" },
  { code: "GBLHR", city: "London (Heathrow)", country: "United Kingdom" },
  { code: "FRLEH", city: "Le Havre", country: "France" },
  { code: "FRFOS", city: "Fos-sur-Mer", country: "France" },
  { code: "FRMRS", city: "Marseille", country: "France" },
  { code: "FRDKK", city: "Dunkerque", country: "France" },
  { code: "FRCDG", city: "Paris (Charles de Gaulle)", country: "France" },
  { code: "ESVLC", city: "Valencia", country: "Spain" },
  { code: "ESBCN", city: "Barcelona", country: "Spain" },
  { code: "ESALG", city: "Algeciras", country: "Spain" },
  { code: "ESBIO", city: "Bilbao", country: "Spain" },
  { code: "ESMAD", city: "Madrid", country: "Spain" },
  { code: "ITGOA", city: "Genoa", country: "Italy" },
  { code: "ITSPE", city: "La Spezia", country: "Italy" },
  { code: "ITGIT", city: "Gioia Tauro", country: "Italy" },
  { code: "ITTRS", city: "Trieste", country: "Italy" },
  { code: "ITLIV", city: "Livorno", country: "Italy" },
  { code: "ITMXP", city: "Milan (Malpensa)", country: "Italy" },
  { code: "PTLIS", city: "Lisbon", country: "Portugal" },
  { code: "PTLEI", city: "Leixoes (Porto)", country: "Portugal" },
  { code: "PTSIE", city: "Sines", country: "Portugal" },
  { code: "GRPIR", city: "Piraeus", country: "Greece" },
  { code: "GRSKG", city: "Thessaloniki", country: "Greece" },
  { code: "MTMAR", city: "Marsaxlokk", country: "Malta" },
  { code: "SIKOP", city: "Koper", country: "Slovenia" },
  { code: "HRRJK", city: "Rijeka", country: "Croatia" },
  { code: "ROCND", city: "Constanta", country: "Romania" },
  { code: "BGVAR", city: "Varna", country: "Bulgaria" },
  { code: "PLGDN", city: "Gdansk", country: "Poland" },
  { code: "PLGDY", city: "Gdynia", country: "Poland" },
  { code: "PLWAW", city: "Warsaw", country: "Poland" },
  { code: "SEGOT", city: "Gothenburg", country: "Sweden" },
  { code: "SESTO", city: "Stockholm", country: "Sweden" },
  { code: "DKAAR", city: "Aarhus", country: "Denmark" },
  { code: "DKCPH", city: "Copenhagen", country: "Denmark" },
  { code: "NOOSL", city: "Oslo", country: "Norway" },
  { code: "FIHEL", city: "Helsinki", country: "Finland" },
  { code: "IEDUB", city: "Dublin", country: "Ireland" },
  { code: "IEORK", city: "Cork", country: "Ireland" },
  { code: "LTKLJ", city: "Klaipeda", country: "Lithuania" },
  { code: "LVRIX", city: "Riga", country: "Latvia" },
  { code: "EETLL", city: "Tallinn", country: "Estonia" },
  { code: "RULED", city: "St Petersburg", country: "Russia" },
  { code: "RUNVS", city: "Novorossiysk", country: "Russia" },
  { code: "RUVVO", city: "Vladivostok", country: "Russia" },
  { code: "RUMOW", city: "Moscow", country: "Russia" },

  // ---- North America ----
  { code: "USNYC", city: "New York / New Jersey", country: "United States" },
  { code: "USLAX", city: "Los Angeles", country: "United States" },
  { code: "USLGB", city: "Long Beach", country: "United States" },
  { code: "USOAK", city: "Oakland", country: "United States" },
  { code: "USSEA", city: "Seattle", country: "United States" },
  { code: "USTIW", city: "Tacoma", country: "United States" },
  { code: "USSAV", city: "Savannah", country: "United States" },
  { code: "USCHS", city: "Charleston", country: "United States" },
  { code: "USORF", city: "Norfolk", country: "United States" },
  { code: "USBAL", city: "Baltimore", country: "United States" },
  { code: "USHOU", city: "Houston", country: "United States" },
  { code: "USMOB", city: "Mobile", country: "United States" },
  { code: "USMIA", city: "Miami", country: "United States" },
  { code: "USJAX", city: "Jacksonville", country: "United States" },
  { code: "USMSY", city: "New Orleans", country: "United States" },
  { code: "USORD", city: "Chicago (O'Hare)", country: "United States" },
  { code: "USATL", city: "Atlanta", country: "United States" },
  { code: "USDFW", city: "Dallas / Fort Worth", country: "United States" },
  { code: "USSFO", city: "San Francisco", country: "United States" },
  { code: "USANC", city: "Anchorage", country: "United States" },
  { code: "USMEM", city: "Memphis", country: "United States" },
  { code: "USSDF", city: "Louisville", country: "United States" },
  { code: "CAVAN", city: "Vancouver", country: "Canada" },
  { code: "CAPRR", city: "Prince Rupert", country: "Canada" },
  { code: "CAMTR", city: "Montreal", country: "Canada" },
  { code: "CAHAL", city: "Halifax", country: "Canada" },
  { code: "CATOR", city: "Toronto", country: "Canada" },
  { code: "MXZLO", city: "Manzanillo", country: "Mexico" },
  { code: "MXLZC", city: "Lazaro Cardenas", country: "Mexico" },
  { code: "MXVER", city: "Veracruz", country: "Mexico" },
  { code: "MXATM", city: "Altamira", country: "Mexico" },
  { code: "MXMEX", city: "Mexico City", country: "Mexico" },
  { code: "PABLB", city: "Balboa", country: "Panama" },
  { code: "PACRI", city: "Cristobal / Colon", country: "Panama" },
  { code: "PAPTY", city: "Panama City", country: "Panama" },

  // ---- Central & South America ----
  { code: "BRSSZ", city: "Santos", country: "Brazil" },
  { code: "BRPNG", city: "Paranagua", country: "Brazil" },
  { code: "BRITJ", city: "Itajai", country: "Brazil" },
  { code: "BRRIG", city: "Rio Grande", country: "Brazil" },
  { code: "BRSSA", city: "Salvador", country: "Brazil" },
  { code: "BRVIX", city: "Vitoria", country: "Brazil" },
  { code: "BRRIO", city: "Rio de Janeiro", country: "Brazil" },
  { code: "BRGRU", city: "Sao Paulo (Guarulhos)", country: "Brazil" },
  { code: "ARBUE", city: "Buenos Aires", country: "Argentina" },
  { code: "UYMVD", city: "Montevideo", country: "Uruguay" },
  { code: "CLVAP", city: "Valparaiso", country: "Chile" },
  { code: "CLSAI", city: "San Antonio", country: "Chile" },
  { code: "CLSCL", city: "Santiago", country: "Chile" },
  { code: "PECLL", city: "Callao (Lima)", country: "Peru" },
  { code: "COCTG", city: "Cartagena", country: "Colombia" },
  { code: "COBUN", city: "Buenaventura", country: "Colombia" },
  { code: "COBOG", city: "Bogota", country: "Colombia" },
  { code: "ECGYE", city: "Guayaquil", country: "Ecuador" },
  { code: "DOCAU", city: "Caucedo", country: "Dominican Republic" },
  { code: "JMKIN", city: "Kingston", country: "Jamaica" },
  { code: "TTPOS", city: "Port of Spain", country: "Trinidad and Tobago" },
  { code: "CRLIO", city: "Moin / Limon", country: "Costa Rica" },

  // ---- Oceania ----
  { code: "AUSYD", city: "Sydney", country: "Australia" },
  { code: "AUMEL", city: "Melbourne", country: "Australia" },
  { code: "AUBNE", city: "Brisbane", country: "Australia" },
  { code: "AUFRE", city: "Fremantle (Perth)", country: "Australia" },
  { code: "AUADL", city: "Adelaide", country: "Australia" },
  { code: "AUDRW", city: "Darwin", country: "Australia" },
  { code: "AUPER", city: "Perth", country: "Australia" },
  { code: "NZAKL", city: "Auckland", country: "New Zealand" },
  { code: "NZTRG", city: "Tauranga", country: "New Zealand" },
  { code: "NZLYT", city: "Lyttelton (Christchurch)", country: "New Zealand" },
  { code: "NZWLG", city: "Wellington", country: "New Zealand" },
];

/** "ZAJNB — Johannesburg (OR Tambo), South Africa" */
export function locodeLabel(l: Locode): string {
  return `${l.code} — ${l.city}, ${l.country}`;
}

/** Datalist option strings, sorted by code. */
export const LOCODE_OPTIONS: string[] = [...LOCODES]
  .sort((a, b) => a.code.localeCompare(b.code))
  .map(locodeLabel);
